list=[1,2,3,4,5,6,7]
print(list)
print(len(list))
# list.reverse()
# print(list)
list.index(1)
print(list.index(2))
list.append(8)
print(list)
list.extend([10,11,12])
print(list)
list.insert(1,20)
print(list)
list.pop()
print(list)
print(list.pop(1))
list.remove(5)
print(list)
list.sort()
print(list)
print(max(list))
print(min(list))
list.clear()
print(list)